// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppGetApiResources() {
  return window['go']['main']['App']['AppGetApiResources']();
}

export function AppGetResourceByName(arg1, arg2) {
  return window['go']['main']['App']['AppGetResourceByName'](arg1, arg2);
}
