// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {v1} from '../models';

export function AppGetApiResources():Promise<Array<v1.APIResource>>;

export function AppGetDeployments():Promise<Array<v1.Deployment>>;
