package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"m8/internal/api/graph/model"
)

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context, name *string, clusterContext string, namespace string) ([]*model.Resource, error) {
	resources, err := r.Clusters[clusterContext].GetResources(*name, namespace)
	return resources, err
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
