package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"m8/internal/api/graph/model"

	"github.com/mitchellh/mapstructure"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/watch"
)

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context, name string, clusterContext string, namespace *string) ([]*model.Resource, error) {
	ns := ""
	if namespace != nil {
		ns = *namespace
	}
	resources, err := r.Clusters[clusterContext].GetResources(name, ns)
	return resources, err
}

// Contexts is the resolver for the contexts field.
func (r *queryResolver) Contexts(ctx context.Context) ([]*string, error) {
	contexts := []*string{}
	i := 0
	for i < len(r.ContextList) {
		strPtr := &r.ContextList[i]
		if *strPtr != "" {
			contexts = append(contexts, strPtr)
		}
		i++
	}
	return contexts, nil
}

// Resources is the resolver for the resources field.
func (r *subscriptionResolver) Resources(ctx context.Context, name string, clusterContext string, namespace *string) (<-chan *model.Resource, error) {
	ns := ""
	if namespace != nil {
		ns = *namespace
	}
	watcher, err := r.Clusters[clusterContext].Watch(name, ns)
	if err != nil {
		// TODO
	}

	eventChannel := make(chan *model.Resource)

	// destructures events and adds objects to the eventChannel that is used in the graphql subscription
	go func(w watch.Interface, eventChannel chan<- *model.Resource) {
		watchChannel := w.ResultChan()
		for {
			select {
			case event := <-watchChannel:
				if event.Object != nil {
					// TODO: when searching for node .. panic: interface conversion: runtime.Object is *v1.Status, not *unstructured.Unstructured
					object := event.Object.(*unstructured.Unstructured).Object

					var resource model.Resource
					// decode unstructured object into resource type
					err = mapstructure.Decode(object, &resource)
					tp := string(event.Type)
					resource.EventType = &tp
					eventChannel <- &resource
				}
			}
		}
	}(watcher, eventChannel)

	return eventChannel, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
